x-common: &x-common
  image: phonebook
  tag: 0.0.10
  config_name: backend

django:
  <<: *x-common
  labels:
    tier: backend
    role: django
  container_name: phonebook-backend
  name: backend
  env:
    DJANGO_SETTINGS_MODULE: phonebook.settings.prod
  command: [/usr/local/bin/gunicorn]
  args: [-b, 0.0.0.0:8000, phonebook.wsgi:application]

celery:
  <<: *x-common
  labels:
    tier: backend
    role: celery
  container_name: celery-backend
  name: celery
  env:
    DJANGO_SETTINGS_MODULE: phonebook.settings.prod
  command: [/usr/local/bin/celery]
  args: [-A, phonebook, worker, -l, debug]

beat:
  <<: *x-common
  replicas: 0
  labels:
    tier: backend
    role: beat
  container_name: beat-backend
  name: beat
  env:
    DJANGO_SETTINGS_MODULE: phonebook.settings.prod
  command: [/usr/local/bin/celery]
  args: [-A, phonebook, beat, -l, debug, --scheduler, django_celery_beat.schedulers:DatabaseScheduler]

flower:
  <<: *x-common
  labels:
    tier: backend
    role: flower
  container_name: celery-backend
  name: flower
  env:
    DJANGO_SETTINGS_MODULE: phonebook.settings.prod
  command: [/usr/local/bin/flower]
  args: [-A, phonebook, --port=5555]