apiVersion: v1
kind: PersistentVolume
metadata:
  name: phonebook-postgres-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    stack: backend
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: manual
  capacity: 
    storage: 5Gi
  hostPath:
    path: "/tmp/pg"