apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phonebook-postgres-data
  labels:
    stack: backend
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 1G
  selector:
    matchLabels:
      stack: backend
  storageClassName: manual
  volumeName: phonebook-postgres-data