apiVersion: v1
kind: Service
metadata:
  name: phonebook-backend
  namespace: phonebook
spec:
  selector:
    tier: backend
    role: django

  type: ClusterIP
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
