apiVersion: v1
kind: Service
metadata:
  name: phonebook-flower-http
  namespace: phonebook
spec:
  selector:
    tier: backend
    role: flower

  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5555
