apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: phonebook
spec:
  selector:
    tier: backend
    role: db

  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432
