apiVersion: v1
kind: Service
metadata:
  name: phonebook-broker
  namespace: phonebook
spec:
  selector:
    tier: backend
    role: broker

  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: phonebook-broker-http
  namespace: phonebook
spec:
  selector:
    tier: backend
    role: broker

  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 15672
