apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: backend
  namespace: phonebook
stringData:
{{- range $k, $v := .Values.backend.secrets }}
  {{ $k }}: {{ $v | quote | indent 1}}
{{- end }}
